Volleyball\Bundle\FacilityBundle\Entity\Department:
    type: entity
    table: department
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        slug:
            type: string
            gedmo:
                slug:
                    fields:
                        - name
    ManyToOne:
        facility:
            targetEntity: Volleyball\Bundle\FacilityBundle\Entity\Facility
            inversedBy: department
            joinColumn:
                name: facility_id
                referencedColumnName: id
        parent:
            targetEntity: Volleyball\Bundle\FacilityBundle\Entity\Department
            inversedBy: department
            referencedColumnName: id
    OneToMany:
        children:
            targetEntity: Volleyball\Bundle\FacilityBundle\Entity\Department
            mappedBy: department