\Volleyball\Bundle\FacilityBundle\Entity\Position:
    type: entity
    table: faculty_position
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        slug:
            type: string
            gedmo:
                slug:
                    fields:
                        - name
    ManyToOne:
        organization:
            targetEntity: Volleyball\Bundle\OrganizationBundle\Entity\Organization
            joinColumn:
                name: organization_id
                referencedColumnName: id
            inversedBy: faculty_position
        parent:
            targetEntity: Volleyball\Bundle\FacilityBundle\Entity\Position
            joinColumn:
                name: parent_id
                referencedColumnName: id
    OneToMany:
        faculty:
            targetEntity: Volleyball\Bundle\FacilityBundle\Entity\Faculty
            mappedBy: faculty_position
        children:
            targetEntity: Volleyball\Bundle\FacilityBundle\Entity\Position
            mappedBy: faculty_position